#!/usr/bin/env ruby
require 'ruby2d'
require './lib/defs.rb'
require './lib/color.rb'
require './lib/game_field.rb'
require './lib/pill.rb'
require './lib/connect_four.rb'
require './lib/viruses.rb'
require './lib/net/producer.rb'
require './lib/net/consumer.rb'
require './lib/sign_in.rb'
require './lib/main_game_loop.rb'
require './lib/net/negotiator.rb'

set title: 'Dr Ruby'
set icon: 'assets/virus_one.png'
set resizable: true

puts get :width


n = Negotiator.new
si = SignIn.new(n)

on :key_down{|k| close if n.player_name = si.handle_input(k['key'])}
on :key_up{|k| si.handle_input_up(k['key'])}

show
clear

n.handoff_user_info
@game_play = GamePlay.new(n)
require './lib/in_game_input.rb'
update do
  next if @game_play.paused
  @game_play.frame
end

show
