# Everytime an Image object was
# being created a warning was generated
# libpng warning: iCCP: known incorrect sRGB profile
# https://stackoverflow.com/questions/22745076/libpng-warning-iccp-known-incorrect-srgb-profile
cleanImages:
	mogrify *.png
